version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: smartistics
      POSTGRES_PASSWORD: smartistics
      POSTGRES_DB: smartistics
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  clickhouse:
    image: clickhouse/clickhouse-server:24
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  attribution:
    build:
      context: ../../services/attribution-py
    ports:
      - "8001:8001"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

volumes:
  postgres_data:
  clickhouse_data:
  redis_data: 